### PR TITLE
Shade jersey dependencies into hpi

### PR DESCRIPTION
**Pull request by mymarche**
Hi, all!

I need some help with this bug.

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by didacrarbones** [comment]
Hi! Any timeline on this being merged and released?

**Comment by mymarche** [comment]
@didacrarbones Hi!
this PR in Draft because it don't working 😞

**Comment by didacrarbones** [comment]
Alright, thanks. I just saw all the checks green and I thought there was something else holding it up.

**Comment by jetersen** [comment]
I don't see a dependency on Jersey. Potentially it would be easier to exclude it from the dependency that is pulling it in transitively, are we sure we even use that dependency even transitively?

**Comment by mymarche** [comment]
@jetersen Yes, i tried to use [jersey2-api-plugin](https://github.com/jenkinsci/jersey2-api-plugin),
but then i cought error in serializing jsons when [jersey2-api-plugin](https://github.com/jenkinsci/jersey2-api-plugin) need some classess from gitlab-api-plugin.

I read [this](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/) and tried to use pluginFirstClassLoader.
But this didn't work too.

**Comment by dcendents** [comment]
I tried pluginFirstClassLoader, I tried shading jersey (needs to be done in `gitlab4j-api` though, not in this plugin), but nothing was working.

I actually found that the problem when using `jersey2-api` is that is also contains `jersey-media-json-binding` and then jersey uses eclipse yasson instead of jackson (I had a `ClassNotFoundException` trying to load an enum from `gitlab4j-api`).

I have open PR #7 which is also in Draft as we need modifications in both `gitlab4j-api` and `jersey2-api`.

**Pull request closed without merging**
